version: '3'
services:
  authelia:
    container_name: authelia    
    image: authelia/authelia:latest
    expose:
      - 9091
    volumes:
      - /home/alan/containers/authelia/config:/config
    environment:
      - TZ=Europe/London
    networks:
      - nginx-proxy-manager_default
    restart: unless-stopped

  redis:
    container_name: redis
    image: redis:alpine
    expose:
      - 6379
    command: redis-server --save 20 1 --loglevel warning --requirepass YOURPASSWORD
    volumes:
      - /home/alan/containers/redis:/data
    environment:
      - TZ=Europe/London
    networks:
      - nginx-proxy-manager_default
    restart: unless-stopped    

networks:
  nginx-proxy-manager_default:
    external: true
    name: nginx-proxy-manager_default          