version: '3'
services:
  auth:
    container_name: auth    
    image: authelia/authelia:latest
    expose:
      - 9091
    volumes:
      - /home/alan/containers/authelia:/config
    networks:
      - nginx-proxy-manager_default
    restart: unless-stopped
    depends_on:
      - redis
      - mariadb

  redis:
    container_name: redis
    image: bitnami/redis:latest
    expose:
      - 6379
    volumes:
      - /home/alan/containers/redis:/bitnami/
    environment:
      REDIS_PASSWORD: "YOUR_REDIS_PASSWORD"
    networks:
      - nginx-proxy-manager_default
    restart: unless-stopped

  mariadb:
    container_name: mariadb
    image: linuxserver/mariadb:latest
    expose:
      - 3306
    volumes:
      - /home/alan/containers/mariadb:/config
    environment:
      MYSQL_ROOT_PASSWORD: "YOUR_MYSQL_ROOT_PASSWORD"
      MYSQL_ROOT_USER: root
      MYSQL_DATABASE: authelia
      MYSQL_USER: authelia
      MYSQL_PASSWORD: "YOUR_MYSQL_USER_PASSWORD"  
    networks:
      - nginx-proxy-manager_default
    restart: unless-stopped

networks:
  nginx-proxy-manager_default:
    external: true
    name: nginx-proxy-manager_default          