services:
  bytestash:
    image: "ghcr.io/jordan-dalby/bytestash:latest"
    container_name: bytestash
    volumes:
      - /home/alan/containers/bytestash:/data/snippets
    expose:
      - 5000
    environment:
      - BASE_PATH=
      # if auth username or password are left blank then authorisation is disabled
      # the username used for logging in
      - AUTH_USERNAME=
      # the password used for logging in
      - AUTH_PASSWORD=
      # the jwt secret used by the server, make sure to generate your own secret token to replace this one
      - JWT_SECRET=[generate JWT token]
      # how long the token lasts, examples: "2 days", "10h", "7d", "1m", "60s"
      - TOKEN_EXPIRY=24h
    restart: unless-stopped
    networks:
      - nginx-proxy-manager_default

networks:
  nginx-proxy-manager_default:
    external: true
    name: nginx-proxy-manager_default    