version: "3"
services:
  dozzle-from-file:
    container_name: dozzle-from-file-diskmonitor
    image: alpine
    volumes:
      - ~/scripts/diskmonitor.log:/var/log/stream.log
    command:
      - tail
      - -f
      - /var/log/stream.log     
    network_mode: none
    restart: unless-stopped