services:
  filebrowser:
    image: gtstef/filebrowser:stable
    volumes:
      - /home/USER/filebrowser-store:/folder # Do not use a root "/" directory or include the "/var" folder | Change USER to the username when using this docker-compose file is being installed
      - /home/USER/containers/filebrowser/data:/home/filebrowser/data # Change USER to the username when using this docker-compose file is being installed
    expose:
      - 80
    environment:
      - TZ=Europe/London
    restart: unless-stopped
    networks:
      - nginx-proxy-manager_default

networks:
  nginx-proxy-manager_default:
    external: true
    name: nginx-proxy-manager_default    