services:
  stirling-pdf:
    container_name: stirling-pdf
    image: stirlingtools/stirling-pdf:latest-ultra-lite
    expose:
      - 8080
    volumes:
      - data:/configs
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false
      - LANGS=en_GB
    restart: unless-stopped
    networks:
      - nginx-proxy-manager_default
volumes:
    data:
networks:
  nginx-proxy-manager_default:
    external: true
    name: nginx-proxy-manager_default