version: "3"
services:
  uptime-kuma:
    command:
      - node
      - server/server.js
    container_name: uptime-kuma
    entrypoint:
      - /usr/bin/dumb-init
      - --
      - extra/entrypoint.sh
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - NODE_VERSION=16.15.0
      - YARN_VERSION=1.22.18
      - TZ=Europe/London
    hostname: 2331f8c6db9c
    image: louislam/uptime-kuma:1
    ipc: private
    logging:
      driver: json-file
      options: {}
    mac_address: 02:42:ac:11:00:04
    expose:
      - 3001/tcp
    restart: unless-stopped
    networks:
      - nginx-proxy-manager_default    
    volumes:
      - /home/alan/containers/uptime-kuma/data:/app/data
    working_dir: /app
networks:
  nginx-proxy-manager_default:
    external: true
    name: nginx-proxy-manager_default