version: "3"
services:
  watchtower:
    command:
      - --include-stopped
      - --debug
    container_name: watchtower
    entrypoint:
      - /watchtower
    environment:
      - WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_NOTIFICATIONS_HOSTNAME=<hostname>
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=<target email>
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=<password>
      - WATCHTOWER_NOTIFICATION_EMAIL_DELAY=2
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=<sending email>
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=<mailserver>
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=587
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=<maillogin>
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - TZ=Europe/London
    expose:
      - 8080/tcp
    hostname: ffbba889a746
    image: containrrr/watchtower
    ipc: private
    labels:
      com.centurylinklabs.watchtower: true
    logging:
      driver: json-file
      options: {}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/alan/.docker/config.json:/config.json
      - /etc/localtime:/etc/localtime:ro
    working_dir: /
    restart: unless-stopped    
networks: {}