---
version: "2.1"
services:
  webtop:
    image: lscr.io/linuxserver/webtop:latest
    container_name: webtop
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - SUBFOLDER=/ #optional
      - KEYBOARD=en-gb-qwerty #optional
    volumes:
      - /home/alan/webtop:/config
      #- /var/run/docker.sock:/var/run/docker.sock #optional
    ports:
      - 3000:3000
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    devices:
      - /dev/dri:/dev/dri #optional
    shm_size: "1gb" #required otherwise web browsers will crash
    restart: "no"
    networks:
      - nginx-proxy-manager_default
networks:
  nginx-proxy-manager_default:
    external: true
    name: nginx-proxy-manager_default    