---
version: "2.1"
services:
  webtop:
    image: lscr.io/linuxserver/webtop:latest
    container_name: webtop
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - SUBFOLDER=/ #optional
      - KEYBOARD=en-us-qwerty #optional
    volumes:
      - /home/alan/containers/webtop:/config
      #- /var/run/docker.sock:/var/run/docker.sock #optional
    ports:
      - 3000:3000
    labels:
      - "com.centurylinklabs.watchtower.enable=false" #to prevent watchtower trying to update the image
    devices:
      - /dev/dri:/dev/dri #optional
    #shm_size: "1gb" #optional
    restart: "no"